projectq/backends/_ibm/_ibm.py
projectq/backends/_ibm/_ibm_http_client.py
projectq/backends/_ibm/_ibm_test.py

These changes would allow you to keep using the IBM connector when the QASM 2.0 API is deployed (coming soon).
It will still work with the current version of the API.

Preparing the IBM format for QASM 2.0 API (it still works with 1.1 API)

---

projectq/backends/_resource.py
projectq/backends/_resource_test.py

This was causing the Shor example to fail in the "lucky guess" case (after I did some refactors to it locally).

Fix ResourceCounter returning None from __str__ when empty

---

projectq/types/_qubit.py
projectq/types/_qubit_test.py

Fixes https://github.com/ProjectQ-Framework/ProjectQ/issues/43

Fix BasicQubit.__hash__ not satisfying a==b implies hash(a)==hash(b)

---

projectq/ops/_basics.py
projectq/ops/_metagates.py
projectq/ops/_metagates_test.py

- Fixed make_tuple_of_qureg assuming first register will contain items
- Fixed ControlledGate overriding __or__ instead of generate_command
- Added test of n=0 case

Fix ControlledGate failing when a register is empty

---

projectq/ops/_gates.py

This allows the simulator to run swaps, instead of requiring them to be decomposed.

Mark SwapGate as a BasicMathGate

---

.travis.yml
projectq/backends/_sim/_cppkernels/simulator.hpp
projectq/backends/_sim/_cppsim.cpp
projectq/backends/_sim/_pysim.py
projectq/backends/_sim/_simulator.py
projectq/backends/_sim/_simulator_test.py

This is the first version of the time evolution emulation feature of the simulator. It works but uses a very loose estimate to rescale the operator H when calculating exp(H). This results in long runtimes for operators featuring a large 1-norm. Later: Include tighter bounds by Al-Mohy & Higham, 2011.

Add a first version of time evolution emulation

---

projectq/backends/_sim/_simulator_test.py
projectq/cengines/_basics.py
projectq/types/_qubit.py
projectq/types/_qubit_test.py

Currently, when the call to `engine.deallocate_qubit` fails, the `self.id = -1` line never runs. The failure can also resurrect the qubit object instance, so its del method gets scheduled to run again, and so an infinite error text loop closes.
Alternatively, the loop can be closed by "helpful" code triggered by the dealloc accidentally calling `__del__` on the qubit.
I've seen it happen (I injected a failure-on-tenth-iteration into LocalOptimizer than ran the Shor example). And this change fixed the problem.

Prevent Qubit.__del__ from running more than once

---

projectq/cengines/_testengine_test.py
projectq/ops/_command_test.py
projectq/types/_qubit.py
projectq/types/_qubit_test.py

When debugging code that generates large circuits, the size of the Qureg descriptions becomes a problem. But most Quregs are sequential, or nearly sequential, and so can be described succinctly as a union of ranges.
For example, instead of:
```
Qureg[0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
```
the code will now say:
```
Qureg[0-6, 8-31]
```

Combine sequential ids into ranges when describing quantum registers

---

projectq/cengines/_optimize.py

- Use slicing and a comprehension instead of index twiddling to count identical gates
- Separate match-finding from match-picking

Minor cleanup in LocalOptimizer._optimize

---

projectq/cengines/_basics.py

- Use guard statement instead of indenting
- Specify dirty tag via `Command.__init__` instead of via CommandModifier
- Merge clean/dirty cases.

Simplify BasicEngine.deallocate_qubit

---

projectq/meta/_compute.py
projectq/meta/_compute_test.py

Checks that `Uncompute(eng)` does not send two `Deallocate` gates when deallocating in fact only one qubit.

Added new test for Compute Uncompute

---

projectq/cengines/_basics.py

If the allocate command could somehow re-enter then this is not a no-op change, but there's no test checking for that behavior so I assume it doesn't happen?

Edit tags directly instead of using CommandModifier in BasicEngine.allocate_qubit

---

projectq/ops/_qubit_operator.py

I improved the implementation of the __isub__ and __sub__ routines in QubitOperator so that several unnecessary copies are avoided. Surprisingly, this optimization led to significantly better performance in some code that Ian and I are working on. One should not simply implement __isub__ as += - QubitOp because that causes an unnecessary copy. In cases where these operators are large, this can create problems. I also added a few spaces to some of the docs as there was inconsistent spacing.

optimized QubitOperator subtraction

---

projectq/backends/_sim/_simulator.py
projectq/setups/decompositions/time_evolution.py
projectq/setups/decompositions/time_evolution_test.py

* Fix two docstrings
* Fixed sparsity warnings by switching to csc matrices

Fix sparsity problems which cause warnings by switching to csc matrices

---

projectq/backends/_sim/_pysim.py
projectq/backends/_sim/_simulator_test.py

If the user specifies a real valued wavefunction, then the internal state of the simulator is changed to numpy float and hence it ignores the complex parts of gates but it always gave a warning if it did.
* Fixed
* Added a test to check for this bug

Bugfix set_wavefunction in pysim

---

projectq/ops/__init__.py
projectq/ops/_basics.py
projectq/ops/_basics_test.py
projectq/ops/_gates.py
projectq/ops/_gates_test.py
projectq/ops/_time_evolution.py

* Introduce BasicPhaseGate which is 2pi periodic. Identical to the BasicRotationGate which is 4pi periodic except the length of the period. One could write, e.g., a metaclass for both cases but not sure if it is worth it.
* Change Ph and R gates to BasicPhaseGate instead of BasicRotationGates. Previous 4pi periodicity instead of 2pi periodicity did not create a bug but just some inefficiencies.
* Tests for Ph and R gates
* Typo in TimeEvolution docs

Ph and R gates are now correctly 2pi periodic instead of 4pi

---

projectq/_version.py
projectq/meta/_compute.py

- Dropped temporary lists because they were references not copies
- Merged id-rewritten into a single nested loop via Command.all_qubits
The `run_uncompute` function is *huge*. This extracts one of its pieces.

Extract _send_rewritten_command from ComputeEngine.run_uncompute

---

projectq/cengines/_replacer/_replacer.py
projectq/cengines/_replacer/_replacer_test.py

* If `AutoReplacer` doesn't find a decomposition rule for a gate class, it checks if there are decomposition rules for the parent classes which might work
* Important change for rules which only require a gate matrix and hence the rule works for all `BasicGate` instances

AutoReplacer checks parent class for replacements

---

projectq/setups/decompositions/__init__.py
projectq/setups/decompositions/cnu2toffoliandcu.py
projectq/setups/decompositions/cnu2toffoliandcu_test.py

* Decomposes multi-controlled gates into single controlled gates
* Uses (n-1) ancilla qubits and 2 * (n-1) Toffoli gates
* Note: We should maybe later separate this rule from the others. It should only be used for hardware, e.g. the IBM setup. There it would make sense to have a first `FilterEngine` which sorts out all gates which have more than 1 control qubit and have an `AutoReplacer` in front of it with this rule (and hopefully soon some more) before an AutoReplacer works on the other rules...
This PR comes after #150

Decompose multi-controlled gates into single controlled gates

---

requirements.txt

Allow newer versions of pybind11 (bug has been fixed).

---

examples/ibm.py
examples/ibm_entangle.ipynb
projectq/backends/_ibm/_ibm.py
projectq/backends/_ibm/_ibm_http_client.py
projectq/backends/_ibm/_ibm_http_client_test.py
projectq/cengines/_ibmcnotmapper.py
projectq/cengines/_ibmcnotmapper_test.py

Apparently, the old way of querying the status is no longer supported. This PR should fix this issue (see #170).
We'll have to wait until ibmqx2 is online again to test if it actually works **before** merging though.

Update to new API for getting the backend status.

---

projectq/backends/_sim/_simulator.py
projectq/backends/_sim/_simulator_test.py

Addresses #175 by raising an exception when the number of qubits does not agree with the size of the gate matrix.

Add simulator exception for incompatible gate size/qubit count.

---

.travis.yml
README.rst
projectq/setups/decompositions/arb1qubit2rzandry.py
projectq/setups/decompositions/arb1qubit2rzandry_test.py

* Removes Python3.3 from the supported Python versions because other packages such as pytest don't work on Python3.3 anymore
* Fixes an infinite recursion loop when decomposing gates

Fix possible infinite recursion loop and drop support for Python 3.3

---

projectq/backends/_resource.py
projectq/ops/_basics.py
projectq/ops/_basics_test.py

Addresses #189 .
I defined the hash of a gate as the hash of its string representation. Note that if a subclass of `BasicGate` (or any class) defines its own `__eq__`, then Python 3 automatically sets its `__hash__` method to `None`, so you need to redefine its `__hash__` method.

Define hash for Gates, use Gate objects as keys in ResourceCounter

---

projectq/backends/_resource.py
projectq/backends/_resource_test.py

Have `ResourceCounter` also keep track of gate classes. Right now the main difference is that it groups together rotation gates of the same type. The new string representation of a `ResourceCounter` begins something like
```
Gate class counts:
AllocateQubitGate : 32
CXGate : 1024
DeallocateQubitGate : 32
HGate : 2048
Rz : 2560
XGate : 16
Gate counts:
Allocate : 32
CX : 1024
Deallocate : 32
H : 2048
Rz(0.09770504) : 1
Rz(0.09817477) : 1
Rz(0.19448398) : 2
...
...[long list of Rz's]
```
Note that the "Gate class counts" section actually appends a `C` to the gate class for each control qubit; otherwise CNOTS would be counted under `XGate`. This is just a choice I made which we can change.

Gate class counts

---

docs/projectq.libs.revkit.rst
docs/projectq.libs.rst
projectq/libs/revkit/__init__.py
projectq/libs/revkit/_permutation.py
projectq/libs/revkit/_permutation_test.py

This contains a first oracle from the RevKit interface, `PermutationOracle`, to automatically synthesise permutations into reversible circuits.

RevKit interface: PermutationOracle

---

projectq/cengines/_main.py
projectq/types/_qubit.py
projectq/types/_qubit_test.py

Removes manually deleted qubits, i.e., user has called qb.__del__(), from active_qubits in MainEngine right away.

Remove manually deallocated qubits from active qubits

---

examples/simulator_tutorial.ipynb
projectq/cengines/_basics.py
projectq/cengines/_main.py
projectq/cengines/_main_test.py
projectq/meta/_compute.py
projectq/meta/_compute_test.py
projectq/meta/_dagger.py
projectq/meta/_dagger_test.py
projectq/setups/decompositions/arb1qubit2rzandry.py

* Stop further exceptions from being thrown once the first exception causes to terminate the program. This includes the case where the first exception is by the user code and not from within ProjectQ.
* Verbose flag for `MainEngine`. By default it is `False` which has the effect that the users only see a shortened stack trace if an exception occurred within ProjectQ. But this compact stack trace should contain all the necessary debug information in most cases.
* When MainEngine goes out of scope, it not only sends a Flush gate but also deallocates all active qubits first
(Addresses first part of #192)

Improved error handling

---

examples/compiler_tutorial.ipynb
examples/ibm.py
examples/ibm16.py
examples/ibm_entangle.ipynb
examples/quantum_random_numbers_ibm.py
examples/teleport.py
examples/teleport_circuit.py
projectq/__init__.py
projectq/cengines/_main.py
projectq/cengines/_main_test.py
projectq/setups/default.py
projectq/setups/ibm.py
projectq/setups/ibm16.py
projectq/setups/ibm16_test.py
projectq/setups/ibm_test.py

This PR addresses the second point in #192: It makes the selection of setups more explicit by adding an additional parameter to `MainEngine`. To select, e.g., the `ibm` setup, one now does
```
from projectq import MainEngine
import projectq.setups.ibm
...
eng = MainEngine(..., setup=projectq.setups.ibm)
...
```

Make the selection of setups (and default engines) more explicit.

---

projectq/backends/_circuits/_to_latex.py
projectq/backends/_circuits/_to_latex_test.py

This PR adds an option to settings.json which forces qubit allocation to happen at x=0 when drawing circuits.

Option to allocate qubits at 0 when drawing circuits.

---

examples/ibm.py
projectq/cengines/_ibmcnotmapper.py

This updates the CNOT direction in the IBMCNOTMapper and thus fixes compilation for the 5-qubit IBM Q backend.

Update CNOT direction of IBM mapper.

---

docs/projectq.setups.rst
examples/ibm.py
examples/ibm16.py
examples/ibm_entangle.ipynb
examples/quantum_random_numbers_ibm.py
projectq/cengines/_main.py
projectq/cengines/_main_test.py
projectq/cengines/_optimize.py

Remove `setup` parameter from MainEngine (has not yet been merged to Master).
This parameter has been introduced to make the compiler engine specifications more explicit instead of just `import projectq.setups.ibm`. Now it is even more explicit: One needs to set the `engine_list` parameter:
```
MainEngine(backend=..., engine_list=projectq.setups.ibm.get_engine_list())
```
Advantages is that one can give the function `get_engine_list` parameters, e.g., we can build a compiler engine setup for a linear chain and give it as a parameter the length of the chain:
```
import projectq.setups.linearchain as linearchain
MainEngine(backend=..., engine_list=linearchain.get_engine_list(num_qubits=8))
```
Downsides:
* It takes a bit more of writing but is much more flexible
* The simplicity of the …

Change setups

---

projectq/backends/_sim/_simulator_test.py
projectq/cengines/_basicmapper.py
projectq/cengines/_ibm5qubitmapper.py
projectq/cengines/_linearmapper.py
projectq/cengines/_linearmapper_test.py
projectq/cengines/_manualmapper.py
projectq/cengines/_twodmapper.py
projectq/cengines/_twodmapper_test.py

Potentially breaking changes (does not affect master branch):
* self.current_mapping is now a property (all ProjectQ mappers are adapted)

Allow arbitrary backend qubit orderings in GridMapper

---

projectq/setups/decompositions/cnu2toffoliandcu.py
projectq/setups/decompositions/cnu2toffoliandcu_test.py

Multi-controlled X-gates are currently decomposed as general controlled U using a Toffoli ladder followed by a CNOT from the final ancilla to the target qubit. This PR improves this slightly by only using Toffoli gates, so the ladder becomes shorter by 1 and thus it requires (n-2) instead of (n-1) ancilla qubits.

Specialize the CnU decomposition rule for Pauli X gates.

---

projectq/backends/_sim/_simulator_test.py
projectq/cengines/_replacer/_replacer_test.py
projectq/ops/_basics.py
projectq/ops/_basics_test.py
projectq/ops/_qftgate.py
projectq/ops/_qftgate_test.py
projectq/setups/decompositions/carb1qubit2cnotrzandry_test.py

In order that user can do:
```
custom_gate = BasicGate()
custom_gate.matrix = numpy.matrix(...)
```
And have a correct `__eq__`

Change BasicGate __eq__ to test for matrix attribute

---

projectq/backends/_ibm/_ibm.py

This fixes #259 by allowing to run trivial circuits on IBM Q, as long as there is at least one measurement.

Allow running trivial circuits on IBM Q

---

projectq/libs/revkit/_control_function.py
projectq/libs/revkit/_permutation.py
projectq/libs/revkit/_phase.py

The updated RevKit library distinguishes between Toffoli circuits and quantum circuits. Therefore,  `write_projectq` needs to know which circuit is addressed. Also, in the updated version `to_projectq()` is a shortcut for `write_projectq(log=True)['contents'])`.

Update to newer RevKit version

---

docs/projectq.setups.decompositions.rst
projectq/setups/decompositions/qubitop2onequbit.py

Update docs of decomposition rules

---

projectq/setups/restrictedgateset.py
projectq/setups/restrictedgateset_test.py

Fixes #290 by no longer allowing controlled versions of supported single-qubit gates when using the `restrictedgateset` setup.

Don't accept controlled single-qubit gates in restricted gate set.

---

docs/projectq.ops.rst
docs/projectq.setups.decompositions.rst
projectq/ops/__init__.py
projectq/ops/_qaagate.py
projectq/ops/_qaagate_test.py
projectq/setups/decompositions/__init__.py
projectq/setups/decompositions/amplitudeamplification.py
projectq/setups/decompositions/amplitudeamplification_test.py
projectq/setups/decompositions/phaseestimation_test.py

Dear friends,
Following the same path I did for Phase Estimation, I would like to add the Amplitude Amplification algorithm as a gate in ops.
Any comment will be welcome.
Thanks

Amplitude Amplification algorithm as a Gate in ops

---

projectq/backends/_resource_test.py
projectq/ops/_gates.py
projectq/ops/_gates_test.py

For convenience, these two-qubit rotation gates might be added to the gate set:
Two-qubit X rotation  exp(-i/2 \theta XX)
Two-qubit Y rotation  exp(-i/2 \theta YY)
Two-qubit Z rotation  exp(-i/2 \theta ZZ)

3 additional 2-qubit gates

---

projectq/backends/_circuits/_drawer.py
projectq/backends/_circuits/_drawer_test.py
projectq/backends/_circuits/_to_latex.py
projectq/backends/_circuits/_to_latex_test.py

Included the possibility to draw the gates in the order they were added to the circuit.
Closes #333

Allow selection of drawing order in CircuitDrawer (solves #333)

---

projectq/backends/_circuits/_drawer_matplotlib.py
projectq/backends/_circuits/_plot.py

- Add missing **kwargs in `draw()` method of `CircuitDrawerMatplotlib`
- Fix bug while drawing if no gate present in the circuit

Fix bugs with matplotlib drawer

---

projectq/backends/__init__.py
projectq/backends/_aqt/__init__.py
projectq/backends/_aqt/_aqt.py
projectq/backends/_aqt/_aqt_http_client.py
projectq/backends/_aqt/_aqt_http_client_test.py
projectq/backends/_aqt/_aqt_test.py
projectq/setups/aqt.py
projectq/setups/aqt_test.py

New Backend to connect to the Alpine Quantum Technologies (AQT) devices.
-> A documentation was released mid-February:
https://www.aqt.eu/aqt-json-tutorial/#json-syntax
-> Access keys can be requested by creating an account at: https://gateway-portal.aqt.eu
->Only tested on the online simulator but the code should be the same for the hardware
->This backend is a trapped ion quantum computer so only accepts Rx,Ry and MS gates

Aqt Backend

---

projectq/backends/_ibm/_ibm_http_client.py

Update the ibmq API as noticed in #378

update on the ibmq client

---

setup.py

Fixes #382 and future proofs in case `platform.mac_ver()[0]` returns `11.x`.

Fix install on macOS Big Sur

---

.github/workflows/ci.yml
.github/workflows/format.yml
.github/workflows/publish_release.yml
.pre-commit-config.yaml
CHANGELOG.md
docs/tutorials.rst
pyproject.toml
setup.cfg
setup.py

- Fix compiler flags cleanup routine for Clang builds
- Fix some errors when running the GitHub actions locally using `act`
- Fix deprecated GitHub Action `pre-commit`
- Update pre-commit hooks

Update CI setup

---

CHANGELOG.md
projectq/backends/_ionq/_ionq_http_client.py
projectq/backends/_ionq/_ionq_http_client_test.py
projectq/setups/ionq.py
projectq/setups/ionq_test.py

Using the backends endpoint, add available backends to the list.

Add support for dynamic backends for IonQ

---

CHANGELOG.md
projectq/backends/_ionq/_ionq_http_client.py
projectq/backends/_ionq/_ionq_http_client_test.py

The previous path was mistakenly incorrect, could we release this as a patch release of project-Q? The previous path 'v0.1/jobs/backends' was mistformatted on a deprecated API.
Happy to help how I can.

IonQ API: Move to v0.2, and fixup backends path
