ProjectQ-Framework/ProjectQ

examples/ibm.py
projectq/_version.py
projectq/backends/_ibm/_ibm.py
projectq/backends/_ibm/_ibm_http_client.py
projectq/backends/_ibm/_ibm_test.py
projectq/cengines/_main.py

Updated the JSON QASM format and added a get_probability function to access the probabilities returned by the IBM Quantum Experience.

Updated the IBMBackend to work with the new API.

---

projectq/cengines/_cmdmodifier.py

Fixes https://github.com/ProjectQ-Framework/ProjectQ/issues/19

Fix CommandModifier forwarding the unmodified list

---

projectq/cengines/_main.py
projectq/cengines/_main_test.py

Shallow copy of engine list.

---

projectq/cengines/_replacer/__init__.py
projectq/cengines/_replacer/_replacer_test.py
projectq/ops/_basics.py
projectq/ops/_metagates.py
projectq/ops/_metagates_test.py

Fixes #37 and a few pep8 issues.

Fixes the controlled gate shortcut.

---

projectq/backends/_circuits/_to_latex.py
projectq/backends/_circuits/_to_latex_test.py

Fixes #52 and adds CZ specialization.

Add CZ and Swap gates to latex drawer.

---

docs/examples.rst
examples/ibm.py
examples/ibm_entangle.ipynb
projectq/backends/_ibm/_ibm.py
projectq/backends/_ibm/_ibm_http_client.py
projectq/backends/_ibm/_ibm_http_client_test.py
projectq/backends/_ibm/_ibm_test.py
projectq/cengines/_ibmcnotmapper.py
projectq/cengines/_ibmcnotmapper_test.py
projectq/meta/__init__.py
projectq/meta/_qubitplacement.py
projectq/meta/_qubitplacement_test.py

Add mapper supporting bow-tie connectivity

---

projectq/backends/_ibm/_ibm_test.py
projectq/ops/_command.py
projectq/ops/_metagates_test.py

And use them in code that was following up the constructor with modifications to those fields.

Add 'controls' and 'tags' parameters to Command.__init__

---

projectq/backends/_sim/_simulator_test.py
projectq/ops/_qubit_operator.py
projectq/ops/_qubit_operator_test.py
projectq/ops/_time_evolution.py

Change init and add a compress function to QubitOperator.

Update QubitOperator: init and compress.

---

projectq/cengines/_optimize.py

- Cut two levels of indentation with a list comprehension

Cleanup LocalOptimizer._send_qubit_pipeline a bit

---

projectq/ops/_time_evolution.py
projectq/ops/_time_evolution_test.py

Can't convert complex to float - made the pull request earlier to the wrong branch

Fixing small TypeError bug in TimeEvolution

---

setup.py

Define requirements only in the `requirements.txt` and read it in the `setup.py` file.

Define requirements only at one place

---

projectq/backends/_sim/_cppkernels/simulator.hpp
projectq/backends/_sim/_cppsim.cpp
projectq/backends/_sim/_pysim.py
projectq/backends/_sim/_simulator.py
projectq/backends/_sim/_simulator_test.py

Added probability and amplitude functions to simulator.

---

projectq/backends/_sim/_cppkernels/simulator.hpp
projectq/backends/_sim/_cppsim.cpp
projectq/backends/_sim/_pysim.py
projectq/backends/_sim/_simulator.py
projectq/backends/_sim/_simulator_test.py

Added set_wavefunction to simulator.

---

projectq/meta/__init__.py
projectq/meta/_compute.py
projectq/meta/_control.py
projectq/meta/_dagger.py
projectq/meta/_loop.py
projectq/meta/_util.py
projectq/meta/_util_test.py

- Use in dagger, loop, control, and compute

Add insert_engine/drop_engine_after meta utility methods

---

projectq/backends/_sim/_cppkernels/simulator.hpp
projectq/backends/_sim/_cppsim.cpp
projectq/backends/_sim/_pysim.py
projectq/backends/_sim/_simulator.py
projectq/backends/_sim/_simulator_test.py

Added collapse_wavefunction to simulator.

---

docs/tutorials.rst

Additional note about hardware specific compilation of the C++ simulator

---

.travis.yml
examples/shor.py
projectq/libs/math/_constantmath.py

Turns warnings into errors. This would have caught #138.
This PR needs to wait until #137 and #138 fix the current warnings.

[After #137 and #138] Turn Warnings into errors

---

README.rst

* Adds a badge for our current pypi version (automatically updated) and linked to pypi
* Adds a static batch displaying our supported python versions

Additional badges

---

projectq/_version.py
projectq/backends/_sim/_pysim.py
projectq/backends/_sim/_simulator_test.py
requirements.txt

* Hotfix pybind workaround
* Bugfix python simulator set_wavefunction

ProjectQ v0.3.3

---

docs/tutorials.rst
projectq/backends/_sim/_cppkernels/simulator.hpp
projectq/backends/_sim/_cppsim.cpp
projectq/backends/_sim/_pysim.py
projectq/backends/_sim/_simulator.py
projectq/backends/_sim/_simulator_test.py

(This is a clean up PR of #131)

Allow applying QubitOperators (even non-unitary).

---

docs/README.rst
docs/tutorials.rst
projectq/backends/_sim/_cppkernels/simulator.hpp
projectq/backends/_sim/_cppsim.cpp
projectq/backends/_sim/_pysim.py
projectq/backends/_sim/_simulator.py
projectq/backends/_sim/_simulator_test.py
projectq/ops/_qubit_operator.py

(This is a clean up PR of #132 and #133)

Readme for docs folder and QubitOperator substraction

---

examples/README.rst
examples/compiler_tutorial.ipynb

* Starting a small tutorial showing the compiler features

Compiler tutorial

---

examples/ibm16.py
projectq/backends/_ibm/_ibm.py
projectq/backends/_ibm/_ibm_http_client.py
projectq/backends/_ibm/_ibm_http_client_test.py
projectq/backends/_ibm/_ibm_test.py
projectq/cengines/__init__.py
projectq/cengines/_ibmcnotmapper.py
projectq/cengines/_manualmapper.py
projectq/cengines/_manualmapper_test.py
projectq/setups/ibm16.py
projectq/setups/ibm16_test.py

Adds a manual mapper and modifies the backend such that it sends jobs rather than individual experiments to the IBM QE. This allows using the 16-qubit chip (after signing up for their beta program).

Adding support for the 16-qubit IBM chip.

---

projectq/ops/_metagates.py
projectq/ops/_metagates_test.py

Add hash function to DaggeredGate.

---

docs/projectq.libs.revkit.rst
projectq/libs/revkit/__init__.py
projectq/libs/revkit/_control_function.py
projectq/libs/revkit/_control_function_test.py
projectq/libs/revkit/_permutation.py
projectq/libs/revkit/_permutation_test.py
projectq/libs/revkit/_phase.py
projectq/libs/revkit/_phase_test.py
projectq/libs/revkit/_utils.py

This function will add "single-target gates", which are gates controlled by an arbitrary control function. The control function is passed as a truth table (in integer notation) or as Python function which is then tried to translate using the `dormouse` module into a truth table.

ControlFunctionOracle

---

projectq/backends/_sim/_simulator.py

Sorry forgot it in the last PR #211

Update docs of simulator init

---

projectq/backends/_sim/_simulator_test.py
requirements.txt

* Fixes issue #220 
* Fixes simulator failure in PR #217

Use new pybind11 version which works with pip >= 10.0.0

---

projectq/cengines/_optimize.py

The previous implementation had a list of lists which grew very large if many qubits were allocated. The new implementation uses a dict for a more compact representation.

Change optimizer from list of lists to dict of lists.

---

.gitignore
docs/conf.py
docs/package_description.py
docs/projectq.rst
projectq/meta/_loop.py
projectq/ops/_command.py

- Generate ReST file in subdirectory to avoid polluting the docs folder
- Fix possible error with builtin Python modules
- Fix error when specifying special members of sub-modules

Fix generated documentation

---

README.rst
examples/aqt.py

bug fix on ibm example (See #367)
new aqt example similar to the ibm one; also added more information to obtain tokens
updated the main README file to reflect updated ibm backend and added mention to aqt backend.
Closes #367

bug fix and AQT tutorial

---

.coveragerc
.travis.yml
projectq/backends/_sim/_pysim.py
projectq/ops/_qubit_operator.py

- Added .coveragerc to ignore test files in coverage
- Cleaned up .travis.yml
- Fixed a couple of bugs leading to test failures
- Added build on Mac OS X (Homebrew)
- Added build on Windows
- Removed Python 2.7 & 3.4 builds as this version has reached its end-of-life

Update .travis.yml configuration & add .coveragerc

---

CHANGELOG.md
projectq/cengines/_main.py
projectq/cengines/_main_test.py
projectq/meta/_util.py
projectq/meta/_util_test.py

Add checks to avoid too many compiler engines in the engine list

---

CHANGELOG.md
setup.py

Fix installation on Apple Silicon and older Python versions
